// Solar System data - planets and celestial bodies
export const solarSystemBodies = [
  {
    id: "sun",
    name: "Sun",
    type: "Star",
    diameter: "1,392,700 km",
    mass: "1.989 × 10³⁰ kg",
    gravity: "274 m/s²",
    temperature: "5,778 K (surface)",
    description: {
      en: "The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.",
      fr: "Le Soleil est l'étoile au centre du système solaire. C'est une sphère presque parfaite de plasma chaud, chauffée à incandescence par des réactions de fusion nucléaire dans son noyau.",
      es: "El Sol es la estrella en el centro del Sistema Solar. Es una esfera casi perfecta de plasma caliente, calentada hasta la incandescencia por reacciones de fusión nuclear en su núcleo.",
      it: "Il Sole è la stella al centro del Sistema Solare. È una sfera quasi perfetta di plasma caldo, riscaldata fino all'incandescenza da reazioni di fusione nucleare nel suo nucleo.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/09/sun-transparent.png",
    color: "#FDB813",
  },
  {
    id: "mercury",
    name: "Mercury",
    type: "Terrestrial Planet",
    diameter: "4,879 km",
    mass: "3.285 × 10²³ kg",
    gravity: "3.7 m/s²",
    distance: "57.9 million km",
    orbitalPeriod: "88 days",
    rotationPeriod: "59 days",
    temperature: "-173°C to 427°C",
    moons: "0",
    atmosphere: "None",
    description: {
      en: "Mercury is the smallest and innermost planet in the Solar System. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the planets.",
      fr: "Mercure est la plus petite et la plus proche planète du Soleil dans le système solaire. Son orbite autour du Soleil prend 87,97 jours terrestres, la plus courte de toutes les planètes.",
      es: "Mercurio es el planeta más pequeño y más interno del Sistema Solar. Su órbita alrededor del Sol toma 87.97 días terrestres, la más corta de todos los planetas.",
      it: "Mercurio è il pianeta più piccolo e più interno del Sistema Solare. La sua orbita intorno al Sole richiede 87,97 giorni terrestri, la più breve di tutti i pianeti.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/05/mercury-transparent.png",
    color: "#8C7853",
  },
  {
    id: "venus",
    name: "Venus",
    type: "Terrestrial Planet",
    diameter: "12,104 km",
    mass: "4.867 × 10²⁴ kg",
    gravity: "8.87 m/s²",
    distance: "108.2 million km",
    orbitalPeriod: "225 days",
    rotationPeriod: "243 days",
    temperature: "462°C",
    moons: "0",
    atmosphere: "CO₂, N₂",
    description: {
      en: "Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. Venus is the hottest planet in the Solar System.",
      fr: "Vénus est la deuxième planète à partir du Soleil. Elle porte le nom de la déesse romaine de l'amour et de la beauté. Vénus est la planète la plus chaude du système solaire.",
      es: "Venus es el segundo planeta desde el Sol. Lleva el nombre de la diosa romana del amor y la belleza. Venus es el planeta más caliente del Sistema Solar.",
      it: "Venere è il secondo pianeta dal Sole. Prende il nome dalla dea romana dell'amore e della bellezza. Venere è il pianeta più caldo del Sistema Solare.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/05/venus-transparent.png",
    color: "#FFC649",
  },
  {
    id: "earth",
    name: "Earth",
    type: "Terrestrial Planet",
    diameter: "12,742 km",
    mass: "5.972 × 10²⁴ kg",
    gravity: "9.807 m/s²",
    distance: "149.6 million km",
    orbitalPeriod: "365.25 days",
    rotationPeriod: "24 hours",
    temperature: "-88°C to 58°C",
    moons: "1 (Moon)",
    atmosphere: "N₂, O₂, Ar",
    description: {
      en: "Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 71% of Earth's surface is water.",
      fr: "La Terre est la troisième planète à partir du Soleil et le seul objet astronomique connu pour abriter la vie. Environ 71% de la surface de la Terre est de l'eau.",
      es: "La Tierra es el tercer planeta desde el Sol y el único objeto astronómico conocido que alberga vida. Aproximadamente el 71% de la superficie de la Tierra es agua.",
      it: "La Terra è il terzo pianeta dal Sole e l'unico oggetto astronomico noto per ospitare la vita. Circa il 71% della superficie terrestre è acqua.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/05/earth-transparent.png",
    color: "#4169E1",
  },
  {
    id: "mars",
    name: "Mars",
    type: "Terrestrial Planet",
    diameter: "6,779 km",
    mass: "6.39 × 10²³ kg",
    gravity: "3.721 m/s²",
    distance: "227.9 million km",
    orbitalPeriod: "687 days",
    rotationPeriod: "24.6 hours",
    temperature: "-153°C to 20°C",
    moons: "2 (Phobos, Deimos)",
    atmosphere: "CO₂, N₂, Ar",
    description: {
      en: "Mars is the fourth planet from the Sun and the second-smallest planet. It is often referred to as the 'Red Planet' due to its reddish appearance.",
      fr: "Mars est la quatrième planète à partir du Soleil et la deuxième plus petite planète. On l'appelle souvent la 'Planète Rouge' en raison de son apparence rougeâtre.",
      es: "Marte es el cuarto planeta desde el Sol y el segundo planeta más pequeño. A menudo se le conoce como el 'Planeta Rojo' debido a su apariencia rojiza.",
      it: "Marte è il quarto pianeta dal Sole e il secondo pianeta più piccolo. È spesso chiamato il 'Pianeta Rosso' a causa del suo aspetto rossastro.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/05/mars-transparent.png",
    color: "#CD5C5C",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    type: "Gas Giant",
    diameter: "139,820 km",
    mass: "1.898 × 10²⁷ kg",
    gravity: "24.79 m/s²",
    distance: "778.5 million km",
    orbitalPeriod: "12 years",
    rotationPeriod: "9.9 hours",
    temperature: "-145°C",
    moons: "95 (Io, Europa, Ganymede, Callisto...)",
    atmosphere: "H₂, He",
    description: {
      en: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets combined.",
      fr: "Jupiter est la cinquième planète à partir du Soleil et la plus grande du système solaire. C'est une géante gazeuse avec une masse plus de deux fois et demie celle de toutes les autres planètes combinées.",
      es: "Júpiter es el quinto planeta desde el Sol y el más grande del Sistema Solar. Es un gigante gaseoso con una masa más de dos veces y media la de todos los demás planetas combinados.",
      it: "Giove è il quinto pianeta dal Sole e il più grande del Sistema Solare. È un gigante gassoso con una massa più di due volte e mezzo quella di tutti gli altri pianeti combinati.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/05/jupiter-transparent.png",
    color: "#DAA520",
  },
  {
    id: "saturn",
    name: "Saturn",
    type: "Gas Giant",
    diameter: "116,460 km",
    mass: "5.683 × 10²⁶ kg",
    gravity: "10.44 m/s²",
    distance: "1.43 billion km",
    orbitalPeriod: "29 years",
    rotationPeriod: "10.7 hours",
    temperature: "-178°C",
    moons: "146 (Titan, Enceladus, Mimas...)",
    atmosphere: "H₂, He",
    description: {
      en: "Saturn is the sixth planet from the Sun and the second-largest. It is a gas giant with an average radius of about nine times that of Earth and is known for its spectacular ring system.",
      fr: "Saturne est la sixième planète à partir du Soleil et la deuxième plus grande. C'est une géante gazeuse avec un rayon moyen d'environ neuf fois celui de la Terre et est connue pour son spectaculaire système d'anneaux.",
      es: "Saturno es el sexto planeta desde el Sol y el segundo más grande. Es un gigante gaseoso con un radio promedio de aproximadamente nueve veces el de la Tierra y es conocido por su espectacular sistema de anillos.",
      it: "Saturno è il sesto pianeta dal Sole e il secondo più grande. È un gigante gassoso con un raggio medio di circa nove volte quello della Terra ed è noto per il suo spettacolare sistema di anelli.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/05/saturn-transparent.png",
    color: "#F4A460",
  },
  {
    id: "uranus",
    name: "Uranus",
    type: "Ice Giant",
    diameter: "50,724 km",
    mass: "8.681 × 10²⁵ kg",
    gravity: "8.69 m/s²",
    distance: "2.87 billion km",
    orbitalPeriod: "84 years",
    rotationPeriod: "17.2 hours",
    temperature: "-224°C",
    moons: "27 (Miranda, Ariel, Umbriel...)",
    atmosphere: "H₂, He, CH₄",
    description: {
      en: "Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass. Uranus is unique as it rotates on its side.",
      fr: "Uranus est la septième planète à partir du Soleil. Elle a le troisième plus grand rayon planétaire et la quatrième plus grande masse planétaire. Uranus est unique car elle tourne sur le côté.",
      es: "Urano es el séptimo planeta desde el Sol. Tiene el tercer radio planetario más grande y la cuarta masa planetaria más grande. Urano es único ya que gira de lado.",
      it: "Urano è il settimo pianeta dal Sole. Ha il terzo raggio planetario più grande e la quarta massa planetaria più grande. Urano è unico in quanto ruota su un lato.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/05/uranus-transparent.png",
    color: "#4FD0E7",
  },
  {
    id: "neptune",
    name: "Neptune",
    type: "Ice Giant",
    diameter: "49,244 km",
    mass: "1.024 × 10²⁶ kg",
    gravity: "11.15 m/s²",
    distance: "4.5 billion km",
    orbitalPeriod: "165 years",
    rotationPeriod: "16.1 hours",
    temperature: "-214°C",
    moons: "14 (Triton, Proteus...)",
    atmosphere: "H₂, He, CH₄",
    description: {
      en: "Neptune is the eighth and farthest known planet from the Sun. It is the fourth-largest planet by diameter and the third-most-massive planet.",
      fr: "Neptune est la huitième et la plus éloignée planète connue du Soleil. C'est la quatrième plus grande planète par diamètre et la troisième planète la plus massive.",
      es: "Neptuno es el octavo y más lejano planeta conocido desde el Sol. Es el cuarto planeta más grande por diámetro y el tercer planeta más masivo.",
      it: "Nettuno è l'ottavo e più lontano pianeta conosciuto dal Sole. È il quarto pianeta più grande per diametro e il terzo pianeta più massiccio.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/05/neptune-transparent.png",
    color: "#4169E1",
  },
  {
    id: "pluto",
    name: "Pluto",
    type: "Dwarf Planet",
    diameter: "2,376 km",
    mass: "1.303 × 10²² kg",
    gravity: "0.62 m/s²",
    distance: "5.9 billion km",
    orbitalPeriod: "248 years",
    rotationPeriod: "6.4 days",
    temperature: "-229°C",
    moons: "5 (Charon, Nix, Hydra...)",
    atmosphere: "N₂, CH₄, CO",
    description: {
      en: "Pluto is a dwarf planet in the Kuiper belt. It was the first Kuiper belt object to be discovered and is the largest known dwarf planet.",
      fr: "Pluton est une planète naine dans la ceinture de Kuiper. C'était le premier objet de la ceinture de Kuiper à être découvert et c'est la plus grande planète naine connue.",
      es: "Plutón es un planeta enano en el cinturón de Kuiper. Fue el primer objeto del cinturón de Kuiper en ser descubierto y es el planeta enano más grande conocido.",
      it: "Plutone è un pianeta nano nella cintura di Kuiper. È stato il primo oggetto della cintura di Kuiper ad essere scoperto ed è il pianeta nano più grande conosciuto.",
    },
    image: "https://science.nasa.gov/wp-content/uploads/2023/06/nh-pluto-in-false-color.png",
    color: "#DEB887",
  },
];

// Function to get planet by ID or name
export const getCelestialBody = (identifier) => {
  const id = identifier.toLowerCase();
  return solarSystemBodies.find(
    (body) => body.id === id || body.name.toLowerCase() === id
  );
};

// Function to search celestial bodies
export const searchCelestialBodies = (query) => {
  const searchTerm = query.toLowerCase();
  return solarSystemBodies.filter((body) =>
    body.name.toLowerCase().includes(searchTerm)
  );
};